version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
          name: run script
          command: |
           ruby ./_scripts/build.rb
      - run:
          name: post blog
          command: |
           git config --global user.email "sikaesi@gmail.com"
           git config --global user.name "sikaesi" 
           git add . 
           git commit -m "[ci skip]"
           git push -f origin master
