version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
           git config --global user.email "sikaesi@gmail.com"
           git config --global user.name "sikaesi" 
           pwd
           ruby ./_scripts/build.rb
           echo "hello!"
           git add . 
           git commit -m "[ci skip]"
           git push -f origin master
